---
- name: Deploy application
  hosts: webservers
  become: yes
  tasks:
    - name: Pull latest docker image
      docker_image:
        name: farul672/vnt_kasir
        tag: "{{ docker_tag }}"
        source: pull

    - name: Run docker container
      docker_container:
        name: vnt_kasir
        image: farul672/vnt_kasir:{{ docker_tag }}
        state: started
        ports:
          - "80:80"
